# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx128m
      TERM: dumb
    
    steps:
      - checkout
      - run:
          command: |
            echo Content of current directory
            ls -al
            echo Switching to java directory
            cd java
            echo Running tests
            gradle test -i
      - store_artifacts:
          path:  java/build/reports/tests/test/

